### ISSUE TITLE
Play 2.4: Guice configuration errors

### ISSUE THREAD

**Issue by matitalatina** [ReactiveMongo/Play-ReactiveMongo#127]
Hi, I'm upgrading my Play project from `2.2.x` to `2.4.0-RC5` and I'm using 
`"org.reactivemongo" %% "play2-reactivemongo" % "0.10.5.0.akka23"`.
Unfortunately when I run the application, which compiles correctly, I have an error at startup.
I think is related to Play-ReactiveMongoPlugin but I can't resolve it.

This is the error shown, can anyone help me? I'm really stuck with it...
```
ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in play.modules.reactivemongo.ReactiveMongoPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at play.modules.reactivemongo.ReactiveMongoPlugin.class(ReactiveMongoPlugin.scala:27)
  while locating play.modules.reactivemongo.ReactiveMongoPlugin

1 error
```

The stack trace is:
```
com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in play.modules.reactivemongo.ReactiveMongoPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at play.modules.reactivemongo.ReactiveMongoPlugin.class(ReactiveMongoPlugin.scala:27)
  while locating play.modules.reactivemongo.ReactiveMongoPlugin

1 error
     com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1042)
     com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1001)
     com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051)
     play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321)
     play.api.Plugins$$anonfun$loadPlugins$1.apply(Plugins.scala:89)
     play.api.Plugins$$anonfun$loadPlugins$1.apply(Plugins.scala:87)
     scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
     scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
     scala.collection.immutable.List.foreach(List.scala:381)
     scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
     scala.collection.immutable.List.map(List.scala:285)
     play.api.Plugins$.loadPlugins(Plugins.scala:87)
     play.api.Plugins$$anonfun$apply$4.apply(Plugins.scala:100)
     play.api.Plugins$$anonfun$apply$4.apply(Plugins.scala:100)
     play.api.Plugins.thePlugins$lzycompute(Plugins.scala:59)
     play.api.Plugins.thePlugins(Plugins.scala:59)
     play.api.Plugins.length(Plugins.scala:60)
     scala.collection.IndexedSeqLike$class.iterator(IndexedSeqLike.scala:90)
     play.api.Plugins.iterator(Plugins.scala:57)
     scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
     play.api.Plugins.foreach(Plugins.scala:57)
     play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
     play.api.Play$$anonfun$start$1.apply(Play.scala:91)
     play.api.Play$$anonfun$start$1.apply(Play.scala:91)
     play.utils.Threads$.withContextClassLoader(Threads.scala:21)
     play.api.Play$.start(Play.scala:90)
     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:156)
     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121)
     scala.Option.map(Option.scala:146)
     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121)
     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119)
     scala.util.Success.flatMap(Try.scala:230)
     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119)
     play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111)
     scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
     scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
     java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
     java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
     java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
     java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
     java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

P.S: If I use `0.11.0-SNAPSHOT` version I have this compilation error
```
[error] missing or invalid dependency detected while loading class file 'JSONGenericHandlers.class'.
[error] Could not access type GenericHandlers in package reactivemongo.api.collections,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'JSONGenericHandlers.class' was compiled against an incompatible version of reactivemongo.api.collections.
```

**Comment by imang** [comment]
+1

**Comment by RadoBuransky** [comment]
This also has been fixed, but needs to be merged: https://github.com/ReactiveMongo/Play-ReactiveMongo/pull/129

**Comment by matitalatina** [comment]
Using your branch I added this resolver:
`"Scalaz Bintray Repo" at "http://dl.bintray.com/scalaz/releases"` otherwise it doesn't find `scalaz`.
It compiles, I published it in my own repository but when I import in in my project I have this following compile error... I don't know how to do... Thanks for your help
```
[info] Compiling 26 Scala sources and 1 Java source to /Users/mattia/Documents/Repositories/ticinotopten/target/scala-2.11/classes...
[error] missing or invalid dependency detected while loading class file 'JSONCollection.class'.
[error] Could not access term reactivemongo in package <root>,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'JSONCollection.class' was compiled against an incompatible version of <root>.
[error] missing or invalid dependency detected while loading class file 'JSONCollection.class'.
[error] Could not access term api in value reactivemongo,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'JSONCollection.class' was compiled against an incompatible version of reactivemongo.
[error] missing or invalid dependency detected while loading class file 'JSONCollection.class'.
[error] Could not access type GenericCollection in value <root>.collections,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'JSONCollection.class' was compiled against an incompatible version of <root>.collections.
[error] missing or invalid dependency detected while loading class file 'JSONGenericHandlers.class'.
[error] Could not access term reactivemongo in package <root>,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'JSONGenericHandlers.class' was compiled against an incompatible version of <root>.
[error] missing or invalid dependency detected while loading class file 'JSONGenericHandlers.class'.
[error] Could not access term api in value reactivemongo,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'JSONGenericHandlers.class' was compiled against an incompatible version of reactivemongo.
[error] missing or invalid dependency detected while loading class file 'JSONGenericHandlers.class'.
[error] Could not access type GenericHandlers in value <root>.collections,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'JSONGenericHandlers.class' was compiled against an incompatible version of <root>.collections.
[error] missing or invalid dependency detected while loading class file 'JSONCollection.class'.
[error] Could not access type CollectionMetaCommands in value <root>.api,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'JSONCollection.class' was compiled against an incompatible version of <root>.api.
[error] missing or invalid dependency detected while loading class file 'package.class'.
[error] Could not access term reactivemongo in package <root>,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of <root>.
[error] missing or invalid dependency detected while loading class file 'package.class'.
[error] Could not access term api in value reactivemongo,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of reactivemongo.
[error] missing or invalid dependency detected while loading class file 'package.class'.
[error] Could not access type GenericCollectionProducer in value <root>.collections,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of <root>.collections.
```

**Comment by matitalatina** [comment]
I solved adding both dependencies in my project: `0.10.5.1.akka23.play24-SNAPSHOT` is my custom version in my own repo.
For now it's working... Thank you very much!
```
"org.reactivemongo"   %% "reactivemongo"  % "0.10.5.0.akka23",
"org.reactivemongo" %% "play2-reactivemongo" % "0.10.5.1.akka23.play24-SNAPSHOT",
```

**Comment by RadoBuransky** [comment]
That was easy. Ha. Thanks

**Comment by cchantep** [comment]
Follow #131
