### ISSUE TITLE
Simple class class cannot be saved in db

### ISSUE THREAD

**Issue by pawank** [ReactiveMongo/Play-ReactiveMongo#157]
Hello,

A simple case class 
<code>
package acelocus.shared
case class User(age: Int, firstName: String, lastName: String)
</code>  
using   
<code>
package acelocus.models.formats
                                                                                                      
import acelocus.shared.User
object JsonFormats {
  import play.api.libs.json.Json
  import play.api.data._
  import play.api.data.Forms._

  // Generates Writes and Reads for Feed and User thanks to Json Macros                                                                                     
  implicit val userFormat = Json.format[User]                                                                                                   
}</code>  
read/write format throws error shown below:
<code>
! @6n5bf51pg - Internal server error, for (GET) [/test/user] ->
 
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: (,List(ValidationError(List(error.expected.jsnumber),WrappedArray())))]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.2.jar:2.4.2]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.2.jar:2.4.2]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.2.jar:2.4.2]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.7.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [scala-library-2.11.7.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.7.jar:na]
Caused by: java.lang.RuntimeException: (,List(ValidationError(List(error.expected.jsnumber),WrappedArray())))
	at scala.sys.package$.error(package.scala:27) ~[scala-library-2.11.7.jar:na]
	at play.modules.reactivemongo.json.JSONSerializationPack$.deserialize(json.scala:377) ~[play2-reactivemongo_2.11-0.11.2.play24.jar:0.11.2.play24]
	at play.modules.reactivemongo.json.JSONSerializationPack$.deserialize(json.scala:350) ~[play2-reactivemongo_2.11-0.11.2.play24.jar:0.11.2.play24]
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:24) ~[reactivemongo_2.11-0.11.2.jar:0.11.2]
	at play.modules.reactivemongo.json.JSONSerializationPack$.readAndDeserialize(json.scala:350) ~[play2-reactivemongo_2.11-0.11.2.play24.jar:0.11.2.play24]
	at reactivemongo.api.SerializationPack$class.readAndDeserialize(serializationpack.scala:32) ~[reactivemongo_2.11-0.11.2.jar:0.11.2]
	at play.modules.reactivemongo.json.JSONSerializationPack$.readAndDeserialize(json.scala:350) ~[play2-reactivemongo_2.11-0.11.2.play24.jar:0.11.2.play24]
	at reactivemongo.api.collections.GenericCollection$$anonfun$insert$1$$anonfun$apply$12.apply(genericcollection.scala:255) ~[reactivemongo_2.11-0.11.2.jar:0.11.2]
	at reactivemongo.api.collections.GenericCollection$$anonfun$insert$1$$anonfun$apply$12.apply(genericcollection.scala:255) ~[reactivemongo_2.11-0.11.2.jar:0.11.2]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[scala-library-2.11.7.jar:na]
</code>
Play controller action used:
<code>
import play.api.data.Form
  import acelocus.shared._
  import acelocus.models.formats.JsonFormats._

  def create = Action.async {
    val user = User(1, "Test", "Test")
    println(s"Saving User - ${user}")
    val futureResult = collection.insert(user)
    // when the insert is performed, send a OK 200 result                                                                                                   
    futureResult.map(_ => Ok)
  }
</code>

Stack used:
Scala 2.11.7
Play 2.4.2
Mongodb 2.6 running at default port.

Any help is appreciated.

**Comment by cchantep** [comment]
Hi, please first ask on the [user MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo). Best regards.
