### ISSUE TITLE
JSON Conversion Fails on BSON Undefined (type 6)

### ISSUE THREAD

**Issue by michaelahlers** [ReactiveMongo/Play-ReactiveMongo#170]
While it's unclear how they came about, I have documents in a collection containing [Mongo's `undefined` type](http://docs.mongodb.org/manual/reference/mongodb-extended-json/#undefined-type) (where the field value is `{"$undefined":true}`)

To illustrate (with gross simplications):

```scala
def collection: BSONCollection = // ...
collection
  .find()
  .cursor[BSONDocument]()
  .enumerate() |>>>
  Iteratee.foreach { document: BSONDocument =>
    println(BSONDocument.pretty(document))
    BSONFormats.toJSON(document)
  }
```

The output from this program is (again, grossly simplified):

```javascript
{
  myField: BSONUndefined
}
```

Followed immediately by:

```
play.modules.reactivemongo.ReactiveMongoPluginException: Unhandled json value: BSONUndefined
	at play.modules.reactivemongo.json.BSONFormats$$anonfun$toJSON$1.apply(json.scala:331) ~[play2-reactivemongo_2.11-0.11.7.play24.jar:0.11.7.play24]
	at play.modules.reactivemongo.json.BSONFormats$$anonfun$toJSON$1.apply(json.scala:331) ~[play2-reactivemongo_2.11-0.11.7.play24.jar:0.11.7.play24]
	at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.7.jar:na]
	at play.modules.reactivemongo.json.BSONFormats$class.toJSON(json.scala:331) ~[play2-reactivemongo_2.11-0.11.7.play24.jar:0.11.7.play24]
	at play.modules.reactivemongo.json.BSONFormats$.toJSON(json.scala:37) ~[play2-reactivemongo_2.11-0.11.7.play24.jar:0.11.7.play24]
	at play.modules.reactivemongo.json.BSONFormats$BSONDocumentFormat$$anonfun$$lessinit$greater$2.apply(json.scala:105) ~[play2-reactivemongo_2.11-0.11.7.play24.jar:0.11.7.play24]
	at play.modules.reactivemongo.json.BSONFormats$BSONDocumentFormat$$anonfun$$lessinit$greater$2.apply(json.scala:105) ~[play2-reactivemongo_2.11-0.11.7.play24.jar:0.11.7.play24]
	at play.modules.reactivemongo.json.BSONFormats$BSONDocumentFormat$$anonfun$json$1.apply(json.scala:102) ~[play2-reactivemongo_2.11-0.11.7.play24.jar:0.11.7.play24]
	at play.modules.reactivemongo.json.BSONFormats$BSONDocumentFormat$$anonfun$json$1.apply(json.scala:102) ~[play2-reactivemongo_2.11-0.11.7.play24.jar:0.11.7.play24]
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418) ~[scala-library-2.11.7.jar:na]
```

Now that we know they're there, we can find and remove these `undefined` values, but it was a tricky bug to investigate and uncover. Is this corect behavior for `play.modules.reactivemongo.json.BSONFormats#toJSON`? (Of course, I'm not sure what the alternative behavior would be. In Play 2.4, ``play.api.libs.json.JsUndefined`` is no longer a meaningful representation of a type like `BSONUndefined`.)

**Comment by arussel** [comment]
@michaelahlers did you find any fix ?

**Comment by cchantep** [comment]
See https://github.com/ReactiveMongo/Reactivemongo-Play-Json/pull/10

**Comment by michaelahlers** [comment]
@arussel, nothing clear-cut. We wound up unsetting fields with `{"$undefined":true}` to get by, and none have appeared since.

**Comment by michaelahlers** [comment]
Funny timing. :smile: Thank you, @cchantep!
