### ISSUE TITLE
DatabaseException['not authorized for query on heroku_appXXX.XXX' (code = 13)]

### ISSUE THREAD

**Issue by loicknuchel** [ReactiveMongo/Play-ReactiveMongo#171]
Hi,

I'm using Heroku & MongoLab for my Play app and since MongoLab upgraded to mongo 3.0.6 I'm unable to authentify properly :(
I'm using Play 2.3.10 & ReactiveMongo 0.11.7 with the Play plugin.

Here is my logs :
```
[ERROR] play - Cannot invoke the action, eventually got an error: reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on heroku_appXXX.Credentials' (code = 13)]
[ERROR] application - 

! @6nji2bmgl - Internal server error, for (POST) [/login] ->

play.api.Application$$anon$1: Execution exception[[DetailedDatabaseException: DatabaseException['not authorized for query on heroku_appXXX.Credentials' (code = 13)]]]
  at play.api.Application$class.handleError(Application.scala:296) ~[com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
  at play.api.DefaultApplication.handleError(Application.scala:402) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
  at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
  at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3$$anonfun$applyOrElse$4.apply(PlayDefaultUpstreamHandler.scala:320) [com.typesafe.play.play_2.11-2.3.10.jar:2.3.10]
  at scala.Option.map(Option.scala:146) [org.scala-lang.scala-library-2.11.6.jar:na]
  at reactivemongo.core.errors.ReactiveMongoException$.apply(errors.scala:32) ~[org.reactivemongo.reactivemongo_2.11-0.11.7.jar:0.11.7]
Caused by: reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on heroku_appXXX.Credentials' (code = 13)]
  at reactivemongo.core.protocol.Response.error$lzycompute(protocol.scala:271) ~[org.reactivemongo.reactivemongo_2.11-0.11.7.jar:0.11.7]
  at reactivemongo.core.protocol.Response.error(protocol.scala:266) ~[org.reactivemongo.reactivemongo_2.11-0.11.7.jar:0.11.7]
  at reactivemongo.core.actors.MongoDBSystem$$anonfun$6.applyOrElse(actors.scala:483) ~[org.reactivemongo.reactivemongo_2.11-0.11.7.jar:0.11.7]
  at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[org.scala-lang.scala-library-2.11.6.jar:na]
```

On my local machine I use mongo 3.0.2 without authentication and all is working well.

I've seen #120 but as I'm on 0.11.7 version, it could be a different issue.
BTW, does ReactiveMongo support **SCRAM-SHA-1** authentication ? If not, how to deal with MONGODB-CR authentication ?

For more details, here is the rights of the user I use :
```
{
    "_id": "heroku_appXXX.heroku_appXXX",
    "user": "heroku_appXXX",
    "db": "heroku_appXXX",
    "credentials": {
        "SCRAM-SHA-1": {
            "iterationCount": 10000,
            "salt": "xxx",
            "storedKey": "xxx",
            "serverKey": "xxx"
        }
    },
    "roles": [
        {
            "role": "dbOwner",
            "db": "heroku_appXXX"
        }
    ]
}
```

Any help will be greatly appreciated :D

**Comment by cchantep** [comment]
Hi, please use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) to ask question (this tracker is for confirmed issue). About the SCRAM-SHA1, yes it's supported, you can find `authMode` in the [documentation](http://reactivemongo.org/releases/0.11/documentation/tutorial/connect-database.html). Best regards.

**Comment by loicknuchel** [comment]
Thanks

**Comment by YA2O** [comment]
Thank you so much for the solution with appending `?authMode=scram-sha1`. It made my day!!! <3
