### ISSUE TITLE
AUTH: error while processing getNonce response #1000

### ISSUE THREAD

**Issue by jieyebing** [ReactiveMongo/Play-ReactiveMongo#191]
mongo 3.2
"org.reactivemongo" %% "reactivemongo" % "0.11.9",
"org.reactivemongo" %% "play2-reactivemongo" % "0.11.9"

i create user on mongodb database，and grant readWrite role to the user. use replicat Set.
Use this user to log on to the mongodb database，all operate everything is OK.
use python access the user's db is successful.
but exception when reactivemongo access the db.use the option : &authMode=scram-sha1
[2016-03-29 08:04:31 +0000] [The node set is now available]
[2016-03-29 08:04:31 +0000] [The primary is now available]
[2016-03-29 08:04:31 +0000] [AUTH: error while processing getNonce response #1000]
[2016-03-29 08:04:31 +0000] [AUTH: error while processing getNonce response #1001]
[2016-03-29 08:04:31 +0000] [AUTH: error while processing getNonce response #1002]
[2016-03-29 08:04:31 +0000] [Cannot invoke the action]
reactivemongo.core.errors.DetailedDatabaseException: DatabaseException['not authorized for query on db_name.collection_name' (code = 13)]
	at reactivemongo.core.errors.ReactiveMongoException$.apply(errors.scala:32) ~[org.reactivemongo.reactivemongo_2.11-0.11.9.jar:0.11.9]
	at reactivemongo.core.protocol.Response.error$lzycompute(protocol.scala:273) ~[org.reactivemongo.reactivemongo_2.11-0.11.9.jar:0.11.9]
	at reactivemongo.core.protocol.Response.error(protocol.scala:268) ~[org.reactivemongo.reactivemongo_2.11-0.11.9.jar:0.11.9]
	at reactivemongo.core.actors.MongoDBSystem$$anonfun$6.applyOrElse(actors.scala:523) ~[org.reactivemongo.reactivemongo_2.11-0.11.9.jar:0.11.9]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at reactivemongo.core.actors.StandardDBSystem.aroundReceive(actors.scala:803) ~[org.reactivemongo.reactivemongo_2.11-0.11.9.jar:0.11.9]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) ~[com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) ~[com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) ~[com.typesafe.akka.akka-actor_2.11-2.3.13.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.7.jar:na]

**Comment by cchantep** [comment]
Hi, please first ask question on the [MailingList]( https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo). Best regards.
