### ISSUE TITLE
add support for Play 2.6

### ISSUE THREAD

**Issue by captainju** [ReactiveMongo/Play-ReactiveMongo#236]
Play 2.6 is about to be released, but Play-ReactiveMongo isn't compatible, here is the stacktrace:

` java.lang.InstantiationError: play.api.libs.json.JsBoolean
	at reactivemongo.play.json.BSONFormats$BSONBooleanFormat$$anonfun$10.applyOrElse(package.scala:284)
	at reactivemongo.play.json.BSONFormats$BSONBooleanFormat$$anonfun$10.applyOrElse(package.scala:283)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:223)
	at scala.PartialFunction$Lifted.apply(PartialFunction.scala:219)
	at reactivemongo.play.json.BSONFormats$class.writeAsJsValue(package.scala:676)
	at reactivemongo.play.json.BSONFormats$.writeAsJsValue(package.scala:93)
	at reactivemongo.play.json.BSONFormats$class.toJSON(package.scala:635)
	at reactivemongo.play.json.BSONFormats$.toJSON(package.scala:93)
	at reactivemongo.play.json.BSONFormats$BSONDocumentFormat$$anonfun$$lessinit$greater$2.apply(package.scala:205)
	at reactivemongo.play.json.BSONFormats$BSONDocumentFormat$$anonfun$$lessinit$greater$2.apply(package.scala:205)
	at reactivemongo.play.json.BSONFormats$BSONDocumentFormat$$anonfun$json$1.apply(package.scala:202)
	at reactivemongo.play.json.BSONFormats$BSONDocumentFormat$$anonfun$json$1.apply(package.scala:202)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
	at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)`

**Comment by captainju** [comment]
sorry wrong project

**Comment by scozv** [comment]
@captainju 

Are you using the `play-reactivemongo` for Play 2.6 now?

I did't find the dependency for Play 2.6.

**Comment by cchantep** [comment]
Hi, please use the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) for discussion.
