### ISSUE TITLE
Play 2.7 support

### ISSUE THREAD

**Issue by riomus** [ReactiveMongo/Play-ReactiveMongo#267]
### ReactiveMongo Version (0.10.5, 0.11.6 / etc)
0.16.1

### MongoDB version (2.6, 3.0 / etc)
Not important
### Operating System (Ubuntu 15.10 / MacOS 10.10 / Windows 10)

Not important

### JDK (Oracle 1.8.0_72, OpenJDK 1.8.x, Azul Zing)

Not important

### Library Dependencies

Play framework 2.7.0

### Expected Behavior

1. There is a release for Play 2.7

### Actual Behavior

1. There is no release for Play 2.7

Currently, there is only 0.16.0-play26 release in maven central. There is no way to use it because it is using global context, even after enabling it, everything fails because of binary incompatibility.

**Comment by mkurz** [comment]
+1 Please add support for Play 2.7 ([without global application](https://www.playframework.com/documentation/2.7.x/Migration27#play.allowGlobalApplication-defaults-to-false))

**Comment by riomus** [comment]
Mentioned binary incompatybility:

`java.lang.NoSuchMethodError: play.api.libs.json.Reads$.traversableReads(Lscala/collection/generic/CanBuildFrom;Lplay/api/libs/json/Reads;)Lplay/api/libs/json/Reads;
        at reactivemongo.play.json.JSONSerializationPack$Decoder$.children(JSONSerializationPack.scala:243)
        at reactivemongo.play.json.JSONSerializationPack$Decoder$.children(JSONSerializationPack.scala:219)
        at reactivemongo.api.commands.CommandCodecs$.$anonfun$defaultWriteResultReader$1(CommandCodecs.scala:36)
        at reactivemongo.api.commands.CommandCodecs$.$anonfun$dealingWithGenericCommandErrorsReader$1(CommandCodecs.scala:19)
        at reactivemongo.play.json.JSONSerializationPack$.$anonfun$reader$1(JSONSerializationPack.scala:157)
        at play.api.libs.json.Reads$$anon$6.reads(Reads.scala:197)
        at reactivemongo.play.json.JSONSerializationPack$.deserialize(JSONSerializationPack.scala:59)
        at reactivemongo.play.json.JSONSerializationPack$.deserialize(JSONSerializationPack.scala:33)
        at reactivemongo.api.SerializationPack.readAndDeserialize(SerializationPack.scala:36)
        at reactivemongo.api.SerializationPack.readAndDeserialize$(SerializationPack.scala:35)
        at reactivemongo.play.json.JSONSerializationPack$.readAndDeserialize(JSONSerializationPack.scala:33)
        at reactivemongo.api.SerializationPack.readAndDeserialize(SerializationPack.scala:40)
        at reactivemongo.api.SerializationPack.readAndDeserialize$(SerializationPack.scala:38)
        at reactivemongo.play.json.JSONSerializationPack$.readAndDeserialize(JSONSerializationPack.scala:33)
        at reactivemongo.api.commands.Command$$anon$2.$anonfun$one$5(commands.scala:147)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
`

**Comment by avdv** [comment]
Hi,

I have prepared a PR for Play 2.7 support as we are currently in the process of upgrading to Play 2.7 and Play-ReactiveMongo is one of the dependencies we need to upgrade.

Tests are green and I did sign the CLA (just in case). See #268

**Comment by mkurz** [comment]
Can be closed. Support for 2.7 was merged.

**Comment by mkurz** [comment]
@cchantep There is no 0.16.2 tag?
https://github.com/ReactiveMongo/Play-ReactiveMongo/releases
